export const cambodiaSchools = [
  // Banteay Meanchey
  {
    value: 'prey-chan-nippon-foundation-school',
    label: 'Prey Chan Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'O Chrov',
  },
  {
    value: 'ta-en-nippon-foundation-school',
    label: 'Ta En Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'Mongkul Borei',
  },
  {
    value: 'dang-run-nippon-foundation-school',
    label: 'Dang Run Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'Mongkul Borei',
  },
  {
    value: 'fumiko-oshima-school',
    label: 'Fumiko Oshima School',
    province: 'Banteay Meanchey',
    district: 'Serei Saôphôn',
  },
  {
    value: 'khi-lek-nippon-foundation-school',
    label: 'Khi Lek Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'Mongkul Borei',
  },
  {
    value: 'khy-lek-kddi-school',
    label: 'Khy Lek KDDI School',
    province: 'Banteay Meanchey',
    district: 'Mongkul Borei',
  },
  {
    value: 'kimiko-morisaki-school-no-one',
    label: 'Kimiko Morisaki School No. One',
    province: 'Banteay Meanchey',
    district: 'Serei Saôphôn',
  },
  {
    value: 'kimiko-morisaki-school-no-two',
    label: 'Kimiko Morisaki School No. Two',
    province: 'Banteay Meanchey',
    district: 'O Chrov',
  },
  {
    value: 'kork-romiet-nippon-foundation-school',
    label: 'Kork Romiet Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'Thmar Pourk',
  },
  {
    value: 'o-sngourt-nippon-foundation-school',
    label: 'O Sngourt Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'Moungkul Borei',
  },
  {
    value: 'phoum-kor-nippon-foundation-school-banteay',
    label: 'Phoum Kor Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'O Chrov',
  },
  {
    value: 'prey-kub-nippon-foundation-school-banteay',
    label: 'Prey Kub Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'O Chrov',
  },
  {
    value: 'snourl-treit-nippon-foundation-school',
    label: 'Snourl Treit Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'O Chrov',
  },
  {
    value: 'tokunori-morisaki-school-no-one',
    label: 'Tokunori Morisaki School No. One',
    province: 'Banteay Meanchey',
    district: 'Serei Saôphôn',
  },
  {
    value: 'tokunori-morisaki-school-no-two',
    label: 'Tokunori Morisaki School No. Two',
    province: 'Banteay Meanchey',
    district: 'Mongkul Borei',
  },
  {
    value: 'yeang-dan-kum-nippon-foundation-school',
    label: 'Yeang Dan Kum Nippon Foundation School',
    province: 'Banteay Meanchey',
    district: 'O Chrov',
  },

  // Battambang
  {
    value: 'angkor-ban-nippon-foundation-school',
    label: 'Angkor Ban Nippon Foundation School',
    province: 'Battambang',
    district: 'Sampouv Loun',
  },
  {
    value: 'arbor-school-of-hope',
    label: 'Arbor School of Hope',
    province: 'Battambang',
    district: 'Phnom Prek',
  },
  {
    value: 'beng-tret-nippon-foundation-school',
    label: 'Beng Tret Nippon Foundation School',
    province: 'Battambang',
    district: 'Sampov Loun',
  },
  {
    value: 'boeung-ktum-nippon-foundation-school',
    label: 'Boeung Ktum Nippon Foundation School',
    province: 'Battambang',
    district: 'Ratanak Mondol',
  },
  {
    value: 'brian-murphy-school',
    label: 'Brian Murphy School',
    province: 'Battambang',
    district: 'Sampouv Loun',
  },
  {
    value: 'cham-ro-a-nippon-foundation-school',
    label: 'Cham Ro A Nippon Foundation School',
    province: 'Battambang',
    district: 'Mong Russei',
  },
  {
    value: 'chork-toch-nippon-foundation-school',
    label: 'Chork Toch Nippon Foundation School',
    province: 'Battambang',
    district: 'Mong Russei',
  },
  {
    value: 'chroy-sdao-nippon-foundation-school',
    label: 'Chroy Sdao Nippon Foundation School',
    province: 'Battambang',
    district: 'Thmat Kol',
  },
  {
    value: 'clark-hamagami-school',
    label: 'Clark Hamagami School',
    province: 'Battambang',
    district: 'Koh Kralor',
  },
  {
    value: 'clumsy-hans-school',
    label: 'Clumsy Hans School',
    province: 'Battambang',
    district: 'Thmar Kaul',
  },
  {
    value: 'daun-bar-nippon-foundation-school',
    label: 'Daun Bar Nippon Foundation School',
    province: 'Battambang',
    district: 'Kas Kra Lar',
  },
  {
    value: 'emperors-new-clothes-school',
    label: "Emperor's New Clothes School",
    province: 'Battambang',
    district: 'Sampov Lun',
  },
  {
    value: 'friends-without-borders-school',
    label: 'Friends Without Borders School',
    province: 'Battambang',
    district: 'Battambang',
  },
  {
    value: 'hong-teuk-nippon-foundation-school',
    label: 'Hong Teuk Nippon Foundation School',
    province: 'Battambang',
    district: 'Phnom Prek',
  },
  {
    value: 'kan-tourth-nippon-foundation-school',
    label: 'Kan Tourth Nippon Foundation School',
    province: 'Battambang',
    district: 'Kas Kra Lar',
  },
  {
    value: 'kbal-thnal-nippon-foundation-school',
    label: 'Kbal Thnal Nippon Foundation School',
    province: 'Battambang',
    district: 'Sangker',
  },
  {
    value: 'kilolek-bourn-nippon-foundation-school',
    label: 'Kilolek Bourn Nippon Foundation School',
    province: 'Battambang',
    district: 'Mong Russei',
  },
  {
    value: 'kok-pon-nippon-foundation-school',
    label: 'Kok Pon Nippon Foundation School',
    province: 'Battambang',
    district: 'Kas Kra Lar',
  },
  {
    value: 'kompong-chamlong-nippon-foundation-school',
    label: 'Kompong Chamlong Nippon Foundation School',
    province: 'Battambang',
    district: 'Kamrieng',
  },
  {
    value: 'komprang-nippon-foundation-school',
    label: 'Komprang Nippon Foundation School',
    province: 'Battambang',
    district: 'Kamrieng',
  },
  {
    value: 'kon-ka-ek-nippon-foundation-school',
    label: 'Kon Ka Ek Nippon Foundation School',
    province: 'Battambang',
    district: 'Mong Russei',
  },
  {
    value: 'masanori-sugihara-school',
    label: 'Masanori Sugihara School',
    province: 'Battambang',
    district: 'Rôtâanak Môndûl',
  },
  {
    value: 'mithapheap-nippon-foundation-school',
    label: 'Mithapheap Nippon Foundation School',
    province: 'Battambang',
    district: 'Kras Krolar',
  },
  {
    value: 'o-ampil-nippon-foundation-school',
    label: 'O Ampil Nippon Foundation School',
    province: 'Battambang',
    district: 'Malay',
  },
  {
    value: 'o-cham-long-nippon-foundation-school',
    label: 'O Cham Long Nippon Foundation School',
    province: 'Battambang',
    district: 'Kamrieng',
  },
  {
    value: 'o-chrey-nippon-foundation-school',
    label: 'O Chrey Nippon Foundation School',
    province: 'Battambang',
    district: 'Kamrieng',
  },
  {
    value: 'o-krieth-nippon-foundation-school',
    label: 'O Krieth Nippon Foundation School',
    province: 'Battambang',
    district: 'Mong Russei',
  },
  {
    value: 'o-lahong-nippon-foundation-school',
    label: 'O Lahong Nippon Foundation School',
    province: 'Battambang',
    district: 'Phnom Prek',
  },
  {
    value: 'o-trav-chu-nippon-foundation-school',
    label: 'O Trav Chu Nippon Foundation School',
    province: 'Battambang',
    district: 'Sampouv Loun',
  },
  {
    value: 'licnoln-sudbury-memorial-school',
    label: 'Licnoln-Sudbury Memorial School',
    province: 'Battambang',
    district: 'Thmar Kaul',
  },
  {
    value: 'phakdei-nippon-foundation-school',
    label: 'Phakdei Nippon Foundation School',
    province: 'Battambang',
    district: 'Ba Nan',
  },
  {
    value: 'phnom-rey-nippon-foundation-school',
    label: 'Phnom Rey Nippon Foundation School',
    province: 'Battambang',
    district: 'Samlot',
  },
  {
    value: 'phnom-touch-nippon-foundation-school',
    label: 'Phnom Touch Nippon Foundation School',
    province: 'Battambang',
    district: 'Phnom Prek',
  },
  {
    value: 'phoum-kor-nippon-foundation-school-battambang',
    label: 'Phoum Kor Nippon Foundation School',
    province: 'Battambang',
    district: 'Mong Russei',
  },
  {
    value: 'prek-am-nippon-foundation-school',
    label: 'Prek Am Nippon Foundation School',
    province: 'Battambang',
    district: 'Mong Russei',
  },
  {
    value: 'sam-seb-nippon-foundation-school',
    label: 'Sam Seb Nippon Foundation School',
    province: 'Battambang',
    district: 'Kamrieng',
  },
  {
    value: 'samlot-nippon-foundation-school',
    label: 'Samlot Nippon Foundation School',
    province: 'Battambang',
    district: 'Samlot',
  },
  {
    value: 'santhipeap-nippon-foundation-school',
    label: 'Santhipeap Nippon Foundation School',
    province: 'Battambang',
    district: 'Samlot',
  },
  {
    value: 'so-o-choam-school',
    label: 'So O Choam School',
    province: 'Battambang',
    district: 'Samlot',
  },
  {
    value: 'sralao-tong-nippon-foundation-school',
    label: 'Sralao Tong Nippon Foundation School',
    province: 'Battambang',
    district: 'Kamrieng',
  },
  {
    value: 'sre-reach-nippon-foundation-school',
    label: 'Sre Reach Nippon Foundation School',
    province: 'Battambang',
    district: 'Samlot',
  },
  {
    value: 'svay-bopharam-nippon-foundation-school',
    label: 'Svay Bopharam Nippon Foundation School',
    province: 'Battambang',
    district: 'Mong Russei',
  },
  {
    value: 'svay-sar-nippon-foundation-school',
    label: 'Svay Sar Nippon Foundation School',
    province: 'Battambang',
    district: 'Sangker',
  },
  {
    value: 'ta-krey-nippon-foundation-school',
    label: 'Ta Krey Nippon Foundation School',
    province: 'Battambang',
    district: 'Kamrieng',
  },
  {
    value: 'ta-sanh-nippon-foundation-school',
    label: 'Ta Sanh Nippon Foundation School',
    province: 'Battambang',
    district: 'Samlot',
  },
  {
    value: 'tasda-nippon-foundation-school',
    label: 'Tasda Nippon Foundation School',
    province: 'Battambang',
    district: 'Sampouv Loun',
  },
  {
    value: 'thmor-baing-don-tret-nippon-foundation-school',
    label: 'Thmor Baing Don Tret Nippon Foundation School',
    province: 'Battambang',
    district: 'Samlot',
  },
  {
    value: 'tinderbox-school',
    label: 'Tinderbox School',
    province: 'Battambang',
    district: 'Kamrieng',
  },
  {
    value: 'wild-swans-school',
    label: 'Wild Swans School',
    province: 'Battambang',
    district: 'Sampov Lun',
  },
  {
    value: 'kdol-doun-teav-secondary-school',
    label: 'Kdol Doun Teav Secondary School',
    province: 'Battambang',
    district: 'Kdol Doun Teav',
  },

  // Kampong Cham
  {
    value: 'aalborg-school-2009',
    label: 'Aalborg School 2009',
    province: 'Kampong Cham',
    district: 'Chamkar Leu',
  },
  {
    value: 'aalborg-school',
    label: 'Aalborg School',
    province: 'Kampong Cham',
    district: 'Thboung Khmum',
  },
  {
    value: 'ang-duong-academy',
    label: 'Ang Duong Academy',
    province: 'Kampong Cham',
    district: 'Koh Sotin',
  },
  {
    value: 'aquas-school-2',
    label: 'Aquas School 2',
    province: 'Kampong Cham',
    district: 'Dember',
  },
  {
    value: 'athletes-foot-school-kampong-cham',
    label: "Athlete's Foot School",
    province: 'Kampong Cham',
    district: 'Krauch Chhmar',
  },
  {
    value: 'black-hawk-school',
    label: 'Black Hawk School',
    province: 'Kampong Cham',
    district: 'Memot',
  },
  {
    value: 'boerne-school-of-hope',
    label: 'Boerne School of Hope',
    province: 'Kampong Cham',
    district: 'Krauch Chhmar',
  },
  {
    value: 'cambridge-school',
    label: 'Cambridge School',
    province: 'Kampong Cham',
    district: 'Cheung Prey',
  },
  {
    value: 'chey-mongkul-nippon-foundation-school',
    label: 'Chey Mongkul Nippon Foundation School',
    province: 'Kampong Cham',
    district: 'Srey Santhor',
  },
  {
    value: 'cincinnati-friendship-school',
    label: 'Cincinnati Friendship School',
    province: 'Kampong Cham',
    district: 'Stung Trang',
  },
  {
    value: 'cocanour-gaudette-family-and-friends-school',
    label: 'Cocanour-Gaudette Family and Friends School',
    province: 'Kampong Cham',
    district: 'Punhear Krek',
  },
  {
    value: 'friendship-school-1',
    label: 'Friendship School 1',
    province: 'Kampong Cham',
    district: 'Damber',
  },
  {
    value: 'friendship-school-2',
    label: 'Friendship School 2',
    province: 'Kampong Cham',
    district: 'Dember',
  },
  {
    value: 'gene-and-nora-hahn-school',
    label: 'Gene and Nora Hahn School',
    province: 'Kampong Cham',
    district: 'Steung Trang',
  },
  {
    value: 'grace-church-school-in-cambodia',
    label: 'Grace Church School in Cambodia',
    province: 'Kampong Cham',
    district: 'Srey Santhor',
  },
  {
    value: 'green-family-school-2',
    label: 'Green Family School 2',
    province: 'Kampong Cham',
    district: 'Tbaung Khmum',
  },
  {
    value: 'guy-leech-school',
    label: 'Guy Leech School',
    province: 'Kampong Cham',
    district: 'Krauch Chhmar',
  },
  {
    value: 'hiroko-okuma-school',
    label: 'Hiroko Okuma School',
    province: 'Kampong Cham',
    district: 'Cheung Prey',
  },
  {
    value: 'karl-mendel-school-2',
    label: 'Karl Mendel School 2',
    province: 'Kampong Cham',
    district: 'Batheay',
  },
  {
    value: 'katsuko-miyagi-school',
    label: 'Katsuko Miyagi School',
    province: 'Kampong Cham',
    district: 'Batheay',
  },
  {
    value: 'kininn-and-ayzas-school-of-hope',
    label: 'Kininn and Ayzas School of Hope',
    province: 'Kampong Cham',
    district: 'Kang Meas',
  },
  {
    value: 'kork-srok-nippon-foundation-school',
    label: 'Kork Srok Nippon Foundation School',
    province: 'Kampong Cham',
    district: 'Dambe',
  },
  {
    value: 'kumomo-tree-one-school',
    label: 'Kumomo Tree One School',
    province: 'Kampong Cham',
    district: 'Batheay',
  },
  {
    value: 'kumomo-tree-two-school',
    label: 'Kumomo Tree Two School',
    province: 'Kampong Cham',
    district: 'Batheay',
  },
  {
    value: 'meyers-family-friendship-school',
    label: 'Meyers Family Friendship School',
    province: 'Kampong Cham',
    district: 'Kampong Siem',
  },
  {
    value: 'milton-school',
    label: 'Milton School',
    province: 'Kampong Cham',
    district: 'Mean',
  },
  {
    value: 'nakry-school',
    label: 'Nakry School',
    province: 'Kampong Cham',
    district: 'Stung Trang',
  },
  {
    value: 'nayoro-keiryo-school',
    label: 'Nayoro Keiryo School',
    province: 'Kampong Cham',
    district: 'Prey Chhor',
  },
  {
    value: 'nightingale-bamford-school-in-cambodia',
    label: 'Nightingale-Bamford School In Cambodia',
    province: 'Kampong Cham',
    district: 'Kampong Siem',
  },
  {
    value: 'o-svay-nippon-foundation-school',
    label: 'O Svay Nippon Foundation School',
    province: 'Kampong Cham',
    district: 'Kang Meas',
  },
  {
    value: 'oconomowoc-sister-school-of-cambodia',
    label: 'Oconomowoc Sister School of Cambodia',
    province: 'Kampong Cham',
    district: 'Prey Chhor',
  },
  {
    value: 'poly-prep-mitapeap-school',
    label: 'Poly Prep Mitapeap School',
    province: 'Kampong Cham',
    district: 'Srey Santhor',
  },
  {
    value: 'prek-koy-school',
    label: 'Prek Koy School',
    province: 'Kampong Cham',
    district: 'Kang Meas',
  },
  {
    value: 'ralph-raphelson-school',
    label: 'Ralph Raphelson School',
    province: 'Kampong Cham',
    district: 'Chamkar Leu',
  },
  {
    value: 'region-rejser-school-no-2',
    label: 'Region Rejser School No. 2',
    province: 'Kampong Cham',
    district: 'Chheung Prey',
  },
  {
    value: 'robert-kiminecz-school-no-1',
    label: 'Robert Kiminecz School No. 1',
    province: 'Kampong Cham',
    district: 'Prey Chhor',
  },
  {
    value: 'rosenfeld-family-school',
    label: 'Rosenfeld Family School',
    province: 'Kampong Cham',
    district: 'Prey Chhor',
  },
  {
    value: 'sakura-school',
    label: 'Sakura School',
    province: 'Kampong Cham',
    district: 'Chamkar Leu',
  },
  {
    value: 'sharing-foundation-school',
    label: 'Sharing Foundation School',
    province: 'Kampong Cham',
    district: 'Batheay',
  },
  {
    value: 'shrenzel-school',
    label: 'Shrenzel School',
    province: 'Kampong Cham',
    district: 'O Raing Euv',
  },
  {
    value: 'sunnyside-school',
    label: 'Sunnyside School',
    province: 'Kampong Cham',
    district: 'Prey Chor',
  },
  {
    value: 'takao-onoda-school',
    label: 'Takao Onoda School',
    province: 'Kampong Cham',
    district: 'Chhoeung Prey',
  },
  {
    value: 'tokatsu-espoir-school',
    label: 'Tokatsu Espoir School',
    province: 'Kampong Cham',
    district: 'Kampong Siem',
  },
  {
    value: 'toranoko-school',
    label: 'Toranoko School',
    province: 'Kampong Cham',
    district: 'Cheung Prey',
  },
  {
    value: 'toshio-nakamura-school',
    label: 'Toshio Nakamura School',
    province: 'Kampong Cham',
    district: 'Batheay',
  },
  {
    value: 'valerie-quirk-school-of-hope',
    label: 'Valerie Quirk School of Hope',
    province: 'Kampong Cham',
    district: 'Korng Meas',
  },
  {
    value: 'wright-family-school',
    label: 'Wright Family School',
    province: 'Kampong Cham',
    district: 'Thboung Khmum',
  },
  {
    value: 'kome-hyappyo-100-sacks-of-rice-school-kampong-cham',
    label: 'Kome Hyappyo (100 Sacks of Rice) School',
    province: 'Kampong Cham',
    district: 'Batheay',
  },
  {
    value: 'maki-school',
    label: 'Maki School',
    province: 'Kampong Cham',
    district: 'Chhoeung Prey',
  },
  {
    value: 'sozaburo-and-yasuko-inoue-school',
    label: 'Sozaburo and Yasuko Inoue School',
    province: 'Kampong Cham',
    district: 'Prey Chhor',
  },
  {
    value: 'yamamoto-and-fujimori-school',
    label: 'Yamamoto and Fujimori School',
    province: 'Kampong Cham',
    district: 'Prey Chhor',
  },

  // Kampong Chhnang
  {
    value: 'aquas-school-3',
    label: 'Aquas School 3',
    province: 'Kampong Chhnang',
    district: "Rolea B'ier",
  },
  {
    value: 'cambodia-hope-school',
    label: 'Cambodia Hope School',
    province: 'Kampong Chhnang',
    district: 'Boribo',
  },
  {
    value: 'jcva-school',
    label: 'JCVA School',
    province: 'Kampong Chhnang',
    district: 'Tek Phos',
  },
  {
    value: 'kunja-school',
    label: 'Kunja School',
    province: 'Kampong Chhnang',
    district: 'Kampong Leng',
  },
  {
    value: 'margaret-derek-jerram-school',
    label: 'Margaret & Derek Jerram School',
    province: 'Kampong Chhnang',
    district: 'Boribo',
  },
  {
    value: 'sasaki-family-school',
    label: 'Sasaki Family School',
    province: 'Kampong Chhnang',
    district: 'Boribo',
  },
  {
    value: 'sharon-a-enright-school-of-hope',
    label: 'Sharon A. Enright School of Hope',
    province: 'Kampong Chhnang',
    district: 'Kampong Chhnang',
  },
  {
    value: 'stand-for-change-school',
    label: 'Stand for Change School',
    province: 'Kampong Chhnang',
    district: 'Kampong Tralach',
  },
  {
    value: 'trapeang-kdar-school',
    label: 'Trapeang Kdar School',
    province: 'Kampong Chhnang',
    district: 'Kampong Tralach',
  },
  {
    value: 'ann-morrison-school',
    label: 'Ann Morrison School',
    province: 'Kampong Chhnang',
    district: 'Tek Phos',
  },
  {
    value: 'lvea-school',
    label: 'Lvea School',
    province: 'Kampong Chhnang',
    district: 'Kompong Leng',
  },
  {
    value: 'world-mate-school-number-three',
    label: 'World Mate School Number Three',
    province: 'Kampong Chhnang',
    district: 'Kompong Leng',
  },

  // Kampong Speu
  {
    value: 'ratanak-grady-grossman-school',
    label: 'Ratanak Grady Grossman School',
    province: 'Kampong Speu',
    district: 'Oral',
  },
  {
    value: 'averbach-popkin-family-school',
    label: 'Averbach/Popkin Family School',
    province: 'Kampong Speu',
    district: 'Barset',
  },
  {
    value: 'clay-alexander-carson-school',
    label: 'Clay Alexander Carson School',
    province: 'Kampong Speu',
    district: 'Samrong Torng',
  },
  {
    value: 'curtis-school',
    label: 'Curtis School',
    province: 'Kampong Speu',
    district: 'Samrong Torng',
  },
  {
    value: 'dahlia-sam-school',
    label: 'Dahlia Sam School',
    province: 'Kampong Speu',
    district: 'Oral',
  },
  {
    value: 'develo-techno-school',
    label: 'Develo Techno School',
    province: 'Kampong Speu',
    district: 'Phnom Srouch',
  },
  {
    value: 'dicheycol-school',
    label: 'Dicheycol School',
    province: 'Kampong Speu',
    district: 'Odong',
  },
  {
    value: 'duke-gandin-memorial-school',
    label: 'Duke Gandin Memorial School',
    province: 'Kampong Speu',
    district: 'Korng Pisei',
  },
  {
    value: 'fcc-school-of-peace',
    label: 'FCC School of Peace',
    province: 'Kampong Speu',
    district: 'Odong',
  },
  {
    value: 'friendship-school-3',
    label: 'Friendship School 3',
    province: 'Kampong Speu',
    district: 'Phnom Srouch',
  },
  {
    value: 'friendship-school-4',
    label: 'Friendship School 4',
    province: 'Kampong Speu',
    district: 'Phnom Srouch',
  },
  {
    value: 'friendship-school-5',
    label: 'Friendship School 5',
    province: 'Kampong Speu',
    district: 'Korng Pisei',
  },
  {
    value: 'gilbert-m-cogan-memorial-school',
    label: 'Gilbert M. Cogan Memorial School',
    province: 'Kampong Speu',
    district: 'Korng Pisei',
  },
  {
    value: 'hardy-and-mcrae-families-school',
    label: 'Hardy and McRae Families School',
    province: 'Kampong Speu',
    district: 'Phnom Srouch',
  },
  {
    value: 'harold-and-elizabeth-m-spector-school',
    label: 'Harold and Elizabeth M. Spector School',
    province: 'Kampong Speu',
    district: 'Korng Pisei',
  },
  {
    value: 'heart-to-heart-school',
    label: 'Heart To Heart School',
    province: 'Kampong Speu',
    district: 'Phnom Sruoch',
  },
  {
    value: 'lux-et-lex-school',
    label: 'Lux et Lex School',
    province: 'Kampong Speu',
    district: 'Oral',
  },
  {
    value: 'noble-path-school',
    label: 'Noble Path School',
    province: 'Kampong Speu',
    district: 'O Dong',
  },
  {
    value: 'paul-and-deborah-kavanaugh-free-academy',
    label: 'Paul and Deborah Kavanaugh Free Academy',
    province: 'Kampong Speu',
    district: 'Odong',
  },
  {
    value: 'peace-school',
    label: 'Peace School',
    province: 'Kampong Speu',
    district: 'Samrong Torng',
  },
  {
    value: 'robert-miller-and-james-zebrowski-memorial-school',
    label: 'Robert Miller and James Zebrowski Memorial School',
    province: 'Kampong Speu',
    district: 'Samrong Torng',
  },
  {
    value: 'salam-national-school-of-cambodia',
    label: 'Salam National School of Cambodia',
    province: 'Kampong Speu',
    district: 'Baset',
  },
  {
    value: 'selva-luna-escuela',
    label: 'Selva Luna Escuela',
    province: 'Kampong Speu',
    district: 'Phnom Sruoch',
  },
  { value: 'shamballa-family-school', label: 'Shamballa Family' },
]
